language: php

php:
  - 7.2
  - 7.3

before_script:
  - printf "\n" | pecl install imagick
  - cp .env.travis .env
  - composer install --no-interaction
  - php artisan key:generate

script:
  - php artisan key:generate
  - vendor/bin/phpunit

cache:
  directories:
    - vendor
