language: php
php:
  - 8.0

cache:
  directories:
    - $HOME/.composer/cache

before_script:
  - sudo apt -y install php8.0-gd
  - cp .env.travis .env
  - composer install
  - php artisan key:generate

script:
  - vendor/bin/phpunit
  - vendor/bin/phpcs --standard=PSR2 app
  - vendor/bin/phpstan analyse
  - vendor/bin/psalm
