language: php
php:
  - 7.4

cache:
  directories:
    - $HOME/.composer/cache

before_script:
  - yes | pecl install imagick
  - cp .env.travis .env
  - composer install
  - php artisan key:generate

script:
  - vendor/bin/phpunit
  - vendor/bin/phpcs --standard=PSR2 app
  - vendor/bin/phpstan analyse
